import streamlit as st
import pickle
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer


ps = PorterStemmer()
STOP_WORDS = set(stopwords.words("english"))


def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)

    text = [
        word
        for word in text
        if word.isalnum() and word not in STOP_WORDS
    ]

    text = [ps.stem(word) for word in text]

    return " ".join(text)


# Load artifacts generated by the DVC pipeline
with open("models/vectorizer.pkl", "rb") as file:
    tfidf = pickle.load(file)

with open("models/model.pkl", "rb") as file:
    model = pickle.load(file)


st.title("Email/SMS Spam Classifier")

input_sms = st.text_area("Enter the message")


if st.button("Predict"):

    if not input_sms.strip():
        st.warning("Please enter a message.")
    else:
        # 1. Preprocess
        transformed_sms = transform_text(input_sms)

        # 2. Vectorize
        vector_input = tfidf.transform(
            [transformed_sms]
        )

        # 3. Predict
        result = model.predict(vector_input)[0]

        # 4. Display result
        if result == 1:
            st.header("Spam")
        else:
            st.header("Not Spam")